export const GET_NOTES = "GET_NOTES";
export const GET_NOTES_ERROR = "GET_NOTES_ERROR";
export const LOADING = "LOADING";

export const CREATE_NOTE = "CREATE_NOTE";
export const CREATE_NOTE_ERROR = "CREATE_NOTE_ERROR";
export const READ_NOTE = "REMOVE_NOTE";
export const READ_NOTE_ERROR = "REMOVE_NOTE_ERROR";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const UPDATE_NOTE_ERROR = "UPDATE_NOTE_ERROR";
export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_NOTE_ERROR = "DELETE_NOTE_ERROR";

export const SELECTED_NOTE = "SELECTED_NOTE";